class Sequences:
    def __init__(self):
        # >Ds-GFP_TAG21 (2165 bp)
        self.dsgfp = "TAGGGATGAAAGTAGGATGGGAAAATCCCGTACCGACCGTTATCGTATAACCGATT" + \
        "TTGTTAGTTTTATCCCGATCGATTTCGAACCCGAGGTAAAAAACGAAAACGGAACGGAAACGGGATATA" + \
        "CAAAACGGTAAACGGAAACGGAAACGGTAGAGCTAGTTTCCCGACCGTTTCACCGGGATCCCGTTTTTA" + \
        "ATCGGAATGATCCCGTTTCGTTACCGTATTTTCTAATTCGGGATGACTGCAATATGGCCAGCTCCAACT" + \
        "CCCATCCATAACCACTGAGGCCCAGCCCATGTAAGAAATACCTAGCGAACGCTGCTCTGCCTCTCTCCC" + \
        "AGGCGGCCAGGCACCACACGAGTAACAGCATCACACATTCACACGCCGCCACGCGCCCACGCCGGAGTC" + \
        "CGGACGCCGCCAGCCGCACGCCGACGCCGGCGACGCGTCTCGCTCTCGCCTGCTCTCTCCGACTCTCCC" + \
        "TGTCTCCCAGCCGGCCGGCCGCTGGGCTGCACCAGGCACCACACGCGGTGACGGCCGTGACGCGGCACG" + \
        "CCGGACGCAGACGCCGCCATCCACGGTCCGCCCTCCACTCCACTGCTCGGCTCTAGCGAAGGGGTTCGA" + \
        "GCTTGGagcttACATGTGTAAAGGTGAAGAGATCTTGCATGTCATTCCACGTAGATAAAAAGAATGCCT" + \
        "ATATAAAAATGGCACATTTTCTTGTAGGTAGTGGAAAGTATCTTTCCAGCAAAGACCATATAATCCGAT" + \
        "AAAGGTGATAACTAAATGTTGAAATCGAGTAGATGCCATATCATCTATACCTTATCTGTTGTTTGGAAA" + \
        "AAAAAGACAAAATCCAAAAAATTTATATGAGATCTCACCTATATAAATAGCGCCCAAATCAGTAGTTAA" + \
        "TCCATCACCCATCTAGAGGATCCCCGGGTACCGGTCGCCACCATGGTGAGCAAGGGCGAGGAGCTGTTC" + \
        "ACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGC" + \
        "GAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCC" + \
        "GTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCAC" + \
        "ATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTC" + \
        "AAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATC" + \
        "GAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAAC" + \
        "AGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCAC" + \
        "AACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCC" + \
        "GTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGC" + \
        "GATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAG" + \
        "TAAAGCGGCCGCGACTCTAGAGTCGACCTGCAGGCATGCAAGCTCGAGTTTCTCCATAATAATGTGTGA" + \
        "GTAGTTCCCAGATAAGGGAATTAGGGTTCCTATAGGGTTTCGCTCATGTGTTGAGCATATAAGAAACCC" + \
        "TTAGTATGTATTTGTATTTGTAAAATACTTCTATCAATAAAATTTCTAATTCCTAAAACCAAAATCCAG" + \
        "TACTAAAATCCAGATCCCCCGAATTCCAAGCTCGAACCCCTTCGCTAGAGCTAAGACTTGTGTTTACAA" + \
        "TTTTTTATATTTGTTTTTAAGTTTTGAATATATGTTTTCATGTGTGATTTTACCGAACAAAAATACCGG" + \
        "TTCCCGTCCGATTTCGACTTTAACCCGACCGGATCGTATCGGTTTTCGATTACCGTATTTATCCCGTTC" + \
        "GTTTTCGTTACCGGTATATCCCGTTTTCGTTTCCGTCCCGCAAGTTAAATATGAAAATGAAAACGGTAG" + \
        "AGGTATTTTACCGACCGTTCCCGACCGTTTTCATCCCTA"


        # >Ds-GFP_TAG21_ReverseComplement  (2165 bp)
        self.dsgfp_revcomp = "TAGGGATGAAAACGGTCGGGAACGGTCGGTAAAATACCTCTACCGTTT" + \
        "TCATTTTCATATTTAACTTGCGGGACGGAAACGAAAACGGGATATACCGGTAACGAAAACGAACGGGAT" + \
        "AAATACGGTAATCGAAAACCGATACGATCCGGTCGGGTTAAAGTCGAAATCGGACGGGAACCGGTATTT" + \
        "TTGTTCGGTAAAATCACACATGAAAACATATATTCAAAACTTAAAAACAAATATAAAAAATTGTAAACA" + \
        "CAAGTCTTAGCTCTAGCGAAGGGGTTCGAGCTTGGAATTCGGGGGATCTGGATTTTAGTACTGGATTTT" + \
        "GGTTTTAGGAATTAGAAATTTTATTGATAGAAGTATTTTACAAATACAAATACATACTAAGGGTTTCTT" + \
        "ATATGCTCAACACATGAGCGAAACCCTATAGGAACCCTAATTCCCTTATCTGGGAACTACTCACACATT" + \
        "ATTATGGAGAAACTCGAGCTTGCATGCCTGCAGGTCGACTCTAGAGTCGCGGCCGCTTTACTTGTACAG" + \
        "CTCGTCCATGCCGAGAGTGATCCCGGCGGCGGTCACGAACTCCAGCAGGACCATGTGATCGCGCTTCTC" + \
        "GTTGGGGTCTTTGCTCAGGGCGGACTGGGTGCTCAGGTAGTGGTTGTCGGGCAGCAGCACGGGGCCGTC" + \
        "GCCGATGGGGGTGTTCTGCTGGTAGTGGTCGGCGAGCTGCACGCTGCCGTCCTCGATGTTGTGGCGGAT" + \
        "CTTGAAGTTCACCTTGATGCCGTTCTTCTGCTTGTCGGCCATGATATAGACGTTGTGGCTGTTGTAGTT" + \
        "GTACTCCAGCTTGTGCCCCAGGATGTTGCCGTCCTCCTTGAAGTCGATGCCCTTCAGCTCGATGCGGTT" + \
        "CACCAGGGTGTCGCCCTCGAACTTCACCTCGGCGCGGGTCTTGTAGTTGCCGTCGTCCTTGAAGAAGAT" + \
        "GGTGCGCTCCTGGACGTAGCCTTCGGGCATGGCGGACTTGAAGAAGTCGTGCTGCTTCATGTGGTCGGG" + \
        "GTAGCGGCTGAAGCACTGCACGCCGTAGGTCAGGGTGGTCACGAGGGTGGGCCAGGGCACGGGCAGCTT" + \
        "GCCGGTGGTGCAGATGAACTTCAGGGTCAGCTTGCCGTAGGTGGCATCGCCCTCGCCCTCGCCGGACAC" + \
        "GCTGAACTTGTGGCCGTTTACGTCGCCGTCCAGCTCGACCAGGATGGGCACCACCCCGGTGAACAGCTC" + \
        "CTCGCCCTTGCTCACCATGGTGGCGACCGGTACCCGGGGATCCTCTAGATGGGTGATGGATTAACTACT" + \
        "GATTTGGGCGCTATTTATATAGGTGAGATCTCATATAAATTTTTTGGATTTTGTCTTTTTTTTCCAAAC" + \
        "AACAGATAAGGTATAGATGATATGGCATCTACTCGATTTCAACATTTAGTTATCACCTTTATCGGATTA" + \
        "TATGGTCTTTGCTGGAAAGATACTTTCCACTACCTACAAGAAAATGTGCCATTTTTATATAGGCATTCT" + \
        "TTTTATCTACGTGGAATGACATGCAAGATCTCTTCACCTTTACACATGTaagctCCAAGCTCGAACCCC" + \
        "TTCGCTAGAGCCGAGCAGTGGAGTGGAGGGCGGACCGTGGATGGCGGCGTCTGCGTCCGGCGTGCCGCG" + \
        "TCACGGCCGTCACCGCGTGTGGTGCCTGGTGCAGCCCAGCGGCCGGCCGGCTGGGAGACAGGGAGAGTC" + \
        "GGAGAGAGCAGGCGAGAGCGAGACGCGTCGCCGGCGTCGGCGTGCGGCTGGCGGCGTCCGGACTCCGGC" + \
        "GTGGGCGCGTGGCGGCGTGTGAATGTGTGATGCTGTTACTCGTGTGGTGCCTGGCCGCCTGGGAGAGAG" + \
        "GCAGAGCAGCGTTCGCTAGGTATTTCTTACATGGGCTGGGCCTCAGTGGTTATGGATGGGAGTTGGAGC" + \
        "TGGCCATATTGCAGTCATCCCGAATTAGAAAATACGGTAACGAAACGGGATCATTCCGATTAAAAACGG" + \
        "GATCCCGGTGAAACGGTCGGGAAACTAGCTCTACCGTTTCCGTTTCCGTTTACCGTTTTGTATATCCCG" + \
        "TTTCCGTTCCGTTTTCGTTTTTTACCTCGGGTTCGAAATCGATCGGGATAAAACTAACAAAATCGGTTA" + \
        "TACGATAACGGTCGGTACGGGATTTTCCCATCCTACTTTCATCCCTA"

        self.gfp3utr = "TGCAAGCTCGAGTTTCTCCA"       # GFP3UTR primer
        self.gfp3utrSize = "750-1000"
        self.gfp3utrHairpin = "24"


        self.dsgg3 = "TTGGAGCTGGCCATATTGCAG"        # 3DsgG primer
        self.dsgg3Size = "425-775"
        self.dsgg3Hairpin = "38"