class Sequences:
    def __init__(self):
        # >Ds-GFP_TAG21 (2165 bp)
        # self.dsgfp is the full GFP sequence on a Ds element on the plus strand.
        self.dsgfp = f"TAGGGATGAAAGTAGGATGGGAAAATCCCGTACCGACCGTTATCGTATAACCGATTTTGTTAGTTTTATCCCGATCGATTTCGAACCCGAGG" + \
            f"TAAAAAACGAAAACGGAACGGAAACGGGATATACAAAACGGTAAACGGAAACGGAAACGGTAGAGCTAGTTTCCCGACCGTTTCACCGGGATCCCGTTTTT" + \
            f"AATCGGAATGATCCCGTTTCGTTACCGTATTTTCTAATTCGGGATGACTGCAATATGGCCAGCTCCAACTCCCATCCATAACCACTGAGGCCCAGCCCATG" + \
            f"TAAGAAATACCTAGCGAACGCTGCTCTGCCTCTCTCCCAGGCGGCCAGGCACCACACGAGTAACAGCATCACACATTCACACGCCGCCACGCGCCCACGCC" + \
            f"GGAGTCCGGACGCCGCCAGCCGCACGCCGACGCCGGCGACGCGTCTCGCTCTCGCCTGCTCTCTCCGACTCTCCCTGTCTCCCAGCCGGCCGGCCGCTGGG" + \
            f"CTGCACCAGGCACCACACGCGGTGACGGCCGTGACGCGGCACGCCGGACGCAGACGCCGCCATCCACGGTCCGCCCTCCACTCCACTGCTCGGCTCTAGCG" + \
            f"AAGGGGTTCGAGCTTGGagcttACATGTGTAAAGGTGAAGAGATCTTGCATGTCATTCCACGTAGATAAAAAGAATGCCTATATAAAAATGGCACATTTTC" + \
            f"TTGTAGGTAGTGGAAAGTATCTTTCCAGCAAAGACCATATAATCCGATAAAGGTGATAACTAAATGTTGAAATCGAGTAGATGCCATATCATCTATACCTT" + \
            f"ATCTGTTGTTTGGAAAAAAAAGACAAAATCCAAAAAATTTATATGAGATCTCACCTATATAAATAGCGCCCAAATCAGTAGTTAATCCATCACCCATCTAG" + \
            f"AGGATCCCCGGGTACCGGTCGCCACCATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGC" + \
            f"CACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCC" + \
            f"CACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCT" + \
            f"ACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTG" + \
            f"AAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAA" + \
            f"CGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCG" + \
            f"TGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCC" + \
            f"GCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAAAGCGGCCGCGACTCTAGAGTCGACCTGCAGGCATGCAAGCTCGAGTTTCTCCATAATAATGT" + \
            f"GTGAGTAGTTCCCAGATAAGGGAATTAGGGTTCCTATAGGGTTTCGCTCATGTGTTGAGCATATAAGAAACCCTTAGTATGTATTTGTATTTGTAAAATAC" + \
            f"TTCTATCAATAAAATTTCTAATTCCTAAAACCAAAATCCAGTACTAAAATCCAGATCCCCCGAATTCCAAGCTCGAACCCCTTCGCTAGAGCTAAGACTTG" + \
            f"TGTTTACAATTTTTTATATTTGTTTTTAAGTTTTGAATATATGTTTTCATGTGTGATTTTACCGAACAAAAATACCGGTTCCCGTCCGATTTCGACTTTAA" + \
            f"CCCGACCGGATCGTATCGGTTTTCGATTACCGTATTTATCCCGTTCGTTTTCGTTACCGGTATATCCCGTTTTCGTTTCCGTCCCGCAAGTTAAATATGAA" + \
            f"AATGAAAACGGTAGAGGTATTTTACCGACCGTTCCCGACCGTTTTCATCCCTA"

        # >Ds-GFP_TAG21_ReverseComplement  (2165 bp)
        # self.dsgfpRevComp is the full GFP sequence on a Ds element on the minus strand.
        self.dsgfpRevComp = f"TAGGGATGAAAACGGTCGGGAACGGTCGGTAAAATACCTCTACCGTTTTCATTTTCATATTTAACTTGCGGGACGGAAACGAAAA" + \
            f"CGGGATATACCGGTAACGAAAACGAACGGGATAAATACGGTAATCGAAAACCGATACGATCCGGTCGGGTTAAAGTCGAAATCGGACGGGAACCGGTATTT" + \
            f"TTGTTCGGTAAAATCACACATGAAAACATATATTCAAAACTTAAAAACAAATATAAAAAATTGTAAACACAAGTCTTAGCTCTAGCGAAGGGGTTCGAGCT" + \
            f"TGGAATTCGGGGGATCTGGATTTTAGTACTGGATTTTGGTTTTAGGAATTAGAAATTTTATTGATAGAAGTATTTTACAAATACAAATACATACTAAGGGT" + \
            f"TTCTTATATGCTCAACACATGAGCGAAACCCTATAGGAACCCTAATTCCCTTATCTGGGAACTACTCACACATTATTATGGAGAAACTCGAGCTTGCATGC" + \
            f"CTGCAGGTCGACTCTAGAGTCGCGGCCGCTTTACTTGTACAGCTCGTCCATGCCGAGAGTGATCCCGGCGGCGGTCACGAACTCCAGCAGGACCATGTGAT" + \
            f"CGCGCTTCTCGTTGGGGTCTTTGCTCAGGGCGGACTGGGTGCTCAGGTAGTGGTTGTCGGGCAGCAGCACGGGGCCGTCGCCGATGGGGGTGTTCTGCTGG" + \
            f"TAGTGGTCGGCGAGCTGCACGCTGCCGTCCTCGATGTTGTGGCGGATCTTGAAGTTCACCTTGATGCCGTTCTTCTGCTTGTCGGCCATGATATAGACGTT" + \
            f"GTGGCTGTTGTAGTTGTACTCCAGCTTGTGCCCCAGGATGTTGCCGTCCTCCTTGAAGTCGATGCCCTTCAGCTCGATGCGGTTCACCAGGGTGTCGCCCT" + \
            f"CGAACTTCACCTCGGCGCGGGTCTTGTAGTTGCCGTCGTCCTTGAAGAAGATGGTGCGCTCCTGGACGTAGCCTTCGGGCATGGCGGACTTGAAGAAGTCG" + \
            f"TGCTGCTTCATGTGGTCGGGGTAGCGGCTGAAGCACTGCACGCCGTAGGTCAGGGTGGTCACGAGGGTGGGCCAGGGCACGGGCAGCTTGCCGGTGGTGCA" + \
            f"GATGAACTTCAGGGTCAGCTTGCCGTAGGTGGCATCGCCCTCGCCCTCGCCGGACACGCTGAACTTGTGGCCGTTTACGTCGCCGTCCAGCTCGACCAGGA" + \
            f"TGGGCACCACCCCGGTGAACAGCTCCTCGCCCTTGCTCACCATGGTGGCGACCGGTACCCGGGGATCCTCTAGATGGGTGATGGATTAACTACTGATTTGG" + \
            f"GCGCTATTTATATAGGTGAGATCTCATATAAATTTTTTGGATTTTGTCTTTTTTTTCCAAACAACAGATAAGGTATAGATGATATGGCATCTACTCGATTT" + \
            f"CAACATTTAGTTATCACCTTTATCGGATTATATGGTCTTTGCTGGAAAGATACTTTCCACTACCTACAAGAAAATGTGCCATTTTTATATAGGCATTCTTT" + \
            f"TTATCTACGTGGAATGACATGCAAGATCTCTTCACCTTTACACATGTaagctCCAAGCTCGAACCCCTTCGCTAGAGCCGAGCAGTGGAGTGGAGGGCGGA" + \
            f"CCGTGGATGGCGGCGTCTGCGTCCGGCGTGCCGCGTCACGGCCGTCACCGCGTGTGGTGCCTGGTGCAGCCCAGCGGCCGGCCGGCTGGGAGACAGGGAGA" + \
            f"GTCGGAGAGAGCAGGCGAGAGCGAGACGCGTCGCCGGCGTCGGCGTGCGGCTGGCGGCGTCCGGACTCCGGCGTGGGCGCGTGGCGGCGTGTGAATGTGTG" + \
            f"ATGCTGTTACTCGTGTGGTGCCTGGCCGCCTGGGAGAGAGGCAGAGCAGCGTTCGCTAGGTATTTCTTACATGGGCTGGGCCTCAGTGGTTATGGATGGGA" + \
            f"GTTGGAGCTGGCCATATTGCAGTCATCCCGAATTAGAAAATACGGTAACGAAACGGGATCATTCCGATTAAAAACGGGATCCCGGTGAAACGGTCGGGAAA" + \
            f"CTAGCTCTACCGTTTCCGTTTCCGTTTACCGTTTTGTATATCCCGTTTCCGTTCCGTTTTCGTTTTTTACCTCGGGTTCGAAATCGATCGGGATAAAACTA" + \
            f"ACAAAATCGGTTATACGATAACGGTCGGTACGGGATTTTCCCATCCTACTTTCATCCCTA"

        self.gfp3utr = "TGCAAGCTCGAGTTTCTCCA"       # GFP3UTR primer
        self.gfp3utrSize = "750-1000"
        self.gfp3utrHairpin = "24"

        self.dsgg3 = "TTGGAGCTGGCCATATTGCAG"        # 3DsgG primer
        self.dsgg3Size = "425-775"
        self.dsgg3Hairpin = "38"