class Sequences:
    def __init__(self):
        # >Ds-GFP_TAG21 (2165 bp)
        self.dsgfp = "TAGGGATGAAAGTAGGATGGGAAAATCCCGTACCGACCGTTATCGTATAACCGATTTTGTTAGTTTTATCCCG" + \
            "ATCGATTTCGAACCCGAGGTAAAAAACGAAAACGGAACGGAAACGGGATATACAAAACGGTAAACGGAAACGGAAACGGTAG" + \
            "AGCTAGTTTCCCGACCGTTTCACCGGGATCCCGTTTTTAATCGGAATGATCCCGTTTCGTTACCGTATTTTCTAATTCGGGA" + \
            "TGACTGCAATATGGCCAGCTCCAACTCCCATCCATAACCACTGAGGCCCAGCCCATGTAAGAAATACCTAGCGAACGCTGCT" + \
            "CTGCCTCTCTCCCAGGCGGCCAGGCACCACACGAGTAACAGCATCACACATTCACACGCCGCCACGCGCCCACGCCGGAGTC" + \
            "CGGACGCCGCCAGCCGCACGCCGACGCCGGCGACGCGTCTCGCTCTCGCCTGCTCTCTCCGACTCTCCCTGTCTCCCAGCCG" + \
            "GCCGGCCGCTGGGCTGCACCAGGCACCACACGCGGTGACGGCCGTGACGCGGCACGCCGGACGCAGACGCCGCCATCCACGG" + \
            "TCCGCCCTCCACTCCACTGCTCGGCTCTAGCGAAGGGGTTCGAGCTTGGagcttACATGTGTAAAGGTGAAGAGATCTTGCA" + \
            "TGTCATTCCACGTAGATAAAAAGAATGCCTATATAAAAATGGCACATTTTCTTGTAGGTAGTGGAAAGTATCTTTCCAGCAA" + \
            "AGACCATATAATCCGATAAAGGTGATAACTAAATGTTGAAATCGAGTAGATGCCATATCATCTATACCTTATCTGTTGTTTG" + \
            "GAAAAAAAAGACAAAATCCAAAAAATTTATATGAGATCTCACCTATATAAATAGCGCCCAAATCAGTAGTTAATCCATCACC" + \
            "CATCTAGAGGATCCCCGGGTACCGGTCGCCACCATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGG" + \
            "TCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGAC" + \
            "CCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGC" + \
            "TTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCA" + \
            "TCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCT" + \
            "GAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATC" + \
            "ATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCG" + \
            "ACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCT" + \
            "GAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGAC" + \
            "GAGCTGTACAAGTAAAGCGGCCGCGACTCTAGAGTCGACCTGCAGGCATGCAAGCTCGAGTTTCTCCATAATAATGTGTGAG" + \
            "TAGTTCCCAGATAAGGGAATTAGGGTTCCTATAGGGTTTCGCTCATGTGTTGAGCATATAAGAAACCCTTAGTATGTATTTG" + \
            "TATTTGTAAAATACTTCTATCAATAAAATTTCTAATTCCTAAAACCAAAATCCAGTACTAAAATCCAGATCCCCCGAATTCC" + \
            "AAGCTCGAACCCCTTCGCTAGAGCTAAGACTTGTGTTTACAATTTTTTATATTTGTTTTTAAGTTTTGAATATATGTTTTCA" + \
            "TGTGTGATTTTACCGAACAAAAATACCGGTTCCCGTCCGATTTCGACTTTAACCCGACCGGATCGTATCGGTTTTCGATTAC" + \
            "CGTATTTATCCCGTTCGTTTTCGTTACCGGTATATCCCGTTTTCGTTTCCGTCCCGCAAGTTAAATATGAAAATGAAAACGG" + \
            "TAGAGGTATTTTACCGACCGTTCCCGACCGTTTTCATCCCTA"

        # >Ds-GFP_TAG21_ReverseComplement  (2165 bp)
        self.dsgfpRevComp = "TAGGGATGAAAACGGTCGGGAACGGTCGGTAAAATACCTCTACCGTTTTCATTTTCATATTTAACT" + \
            "TGCGGGACGGAAACGAAAACGGGATATACCGGTAACGAAAACGAACGGGATAAATACGGTAATCGAAAACCGATACGATCCG" + \
            "GTCGGGTTAAAGTCGAAATCGGACGGGAACCGGTATTTTTGTTCGGTAAAATCACACATGAAAACATATATTCAAAACTTAA" + \
            "AAACAAATATAAAAAATTGTAAACACAAGTCTTAGCTCTAGCGAAGGGGTTCGAGCTTGGAATTCGGGGGATCTGGATTTTA" + \
            "GTACTGGATTTTGGTTTTAGGAATTAGAAATTTTATTGATAGAAGTATTTTACAAATACAAATACATACTAAGGGTTTCTTA" + \
            "TATGCTCAACACATGAGCGAAACCCTATAGGAACCCTAATTCCCTTATCTGGGAACTACTCACACATTATTATGGAGAAACT" + \
            "CGAGCTTGCATGCCTGCAGGTCGACTCTAGAGTCGCGGCCGCTTTACTTGTACAGCTCGTCCATGCCGAGAGTGATCCCGGC" + \
            "GGCGGTCACGAACTCCAGCAGGACCATGTGATCGCGCTTCTCGTTGGGGTCTTTGCTCAGGGCGGACTGGGTGCTCAGGTAG" + \
            "TGGTTGTCGGGCAGCAGCACGGGGCCGTCGCCGATGGGGGTGTTCTGCTGGTAGTGGTCGGCGAGCTGCACGCTGCCGTCCT" + \
            "CGATGTTGTGGCGGATCTTGAAGTTCACCTTGATGCCGTTCTTCTGCTTGTCGGCCATGATATAGACGTTGTGGCTGTTGTA" + \
            "GTTGTACTCCAGCTTGTGCCCCAGGATGTTGCCGTCCTCCTTGAAGTCGATGCCCTTCAGCTCGATGCGGTTCACCAGGGTG" + \
            "TCGCCCTCGAACTTCACCTCGGCGCGGGTCTTGTAGTTGCCGTCGTCCTTGAAGAAGATGGTGCGCTCCTGGACGTAGCCTT" + \
            "CGGGCATGGCGGACTTGAAGAAGTCGTGCTGCTTCATGTGGTCGGGGTAGCGGCTGAAGCACTGCACGCCGTAGGTCAGGGT" + \
            "GGTCACGAGGGTGGGCCAGGGCACGGGCAGCTTGCCGGTGGTGCAGATGAACTTCAGGGTCAGCTTGCCGTAGGTGGCATCG" + \
            "CCCTCGCCCTCGCCGGACACGCTGAACTTGTGGCCGTTTACGTCGCCGTCCAGCTCGACCAGGATGGGCACCACCCCGGTGA" + \
            "ACAGCTCCTCGCCCTTGCTCACCATGGTGGCGACCGGTACCCGGGGATCCTCTAGATGGGTGATGGATTAACTACTGATTTG" + \
            "GGCGCTATTTATATAGGTGAGATCTCATATAAATTTTTTGGATTTTGTCTTTTTTTTCCAAACAACAGATAAGGTATAGATG" + \
            "ATATGGCATCTACTCGATTTCAACATTTAGTTATCACCTTTATCGGATTATATGGTCTTTGCTGGAAAGATACTTTCCACTA" + \
            "CCTACAAGAAAATGTGCCATTTTTATATAGGCATTCTTTTTATCTACGTGGAATGACATGCAAGATCTCTTCACCTTTACAC" + \
            "ATGTaagctCCAAGCTCGAACCCCTTCGCTAGAGCCGAGCAGTGGAGTGGAGGGCGGACCGTGGATGGCGGCGTCTGCGTCC" + \
            "GGCGTGCCGCGTCACGGCCGTCACCGCGTGTGGTGCCTGGTGCAGCCCAGCGGCCGGCCGGCTGGGAGACAGGGAGAGTCGG" + \
            "AGAGAGCAGGCGAGAGCGAGACGCGTCGCCGGCGTCGGCGTGCGGCTGGCGGCGTCCGGACTCCGGCGTGGGCGCGTGGCGG" + \
            "CGTGTGAATGTGTGATGCTGTTACTCGTGTGGTGCCTGGCCGCCTGGGAGAGAGGCAGAGCAGCGTTCGCTAGGTATTTCTT" + \
            "ACATGGGCTGGGCCTCAGTGGTTATGGATGGGAGTTGGAGCTGGCCATATTGCAGTCATCCCGAATTAGAAAATACGGTAAC" + \
            "GAAACGGGATCATTCCGATTAAAAACGGGATCCCGGTGAAACGGTCGGGAAACTAGCTCTACCGTTTCCGTTTCCGTTTACC" + \
            "GTTTTGTATATCCCGTTTCCGTTCCGTTTTCGTTTTTTACCTCGGGTTCGAAATCGATCGGGATAAAACTAACAAAATCGGT" + \
            "TATACGATAACGGTCGGTACGGGATTTTCCCATCCTACTTTCATCCCTA"

        self.gfp3utr = "TGCAAGCTCGAGTTTCTCCA"       # GFP3UTR primer
        self.gfp3utrSize = "750-1000"
        self.gfp3utrHairpin = "24"

        self.dsgg3 = "TTGGAGCTGGCCATATTGCAG"        # 3DsgG primer
        self.dsgg3Size = "425-775"
        self.dsgg3Hairpin = "38"