class Sequences:
    def __init__(self):
        # >Ds-GFP_TAG21 (2165 bp)

        self.dsgfp = \
            "TAGGGATGAAAGTAGGATGGGAAAATCCCGTACCGACCGTTATCGTATAACCGATTTTGTTAGTTTTATCCCGATCGATTTCGAACCCGAGGT" + \
                     "AAAAAACGAAAACGGAACGGAAACGGGATATACAAAACGGTAAACGGAAACGGAAACGGTAGAGCTAGTTTCCCGACCGTTTCACCGGGATCCCGTTTTTAA" + \
                     "TCGGAATGATCCCGTTTCGTTACCGTATTTTCTAATTCGGGATGACTGCAATATGGCCAGCTCCAACTCCCATCCATAACCACTGAGGCCCAGCCCATGTAA" + \
                     "GAAATACCTAGCGAACGCTGCTCTGCCTCTCTCCCAGGCGGCCAGGCACCACACGAGTAACAGCATCACACATTCACACGCCGCCACGCGCCCACGCCGGAG" + \
                     "TCCGGACGCCGCCAGCCGCACGCCGACGCCGGCGACGCGTCTCGCTCTCGCCTGCTCTCTCCGACTCTCCCTGTCTCCCAGCCGGCCGGCCGCTGGGCTGCA" + \
                     "CCAGGCACCACACGCGGTGACGGCCGTGACGCGGCACGCCGGACGCAGACGCCGCCATCCACGGTCCGCCCTCCACTCCACTGCTCGGCTCTAGCGAAGGGG" + \
                     "TTCGAGCTTGGagcttACATGTGTAAAGGTGAAGAGATCTTGCATGTCATTCCACGTAGATAAAAAGAATGCCTATATAAAAATGGCACATTTTCTTGTAGG" + \
                     "TAGTGGAAAGTATCTTTCCAGCAAAGACCATATAATCCGATAAAGGTGATAACTAAATGTTGAAATCGAGTAGATGCCATATCATCTATACCTTATCTGTTG" + \
                     "TTTGGAAAAAAAAGACAAAATCCAAAAAATTTATATGAGATCTCACCTATATAAATAGCGCCCAAATCAGTAGTTAATCCATCACCCATCTAGAGGATCCCC" + \
                     "GGGTACCGGTCGCCACCATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCA" + \
                     "GCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGA" + \
                     "CCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGC" + \
                     "GCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACT" + \
                     "TCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGA" + \
                     "ACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACA" + \
                     "ACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCG" + \
                     "GCATGGACGAGCTGTACAAGTAAAGCGGCCGCGACTCTAGAGTCGACCTGCAGGCATGCAAGCTCGAGTTTCTCCATAATAATGTGTGAGTAGTTCCCAGAT" + \
                     "AAGGGAATTAGGGTTCCTATAGGGTTTCGCTCATGTGTTGAGCATATAAGAAACCCTTAGTATGTATTTGTATTTGTAAAATACTTCTATCAATAAAATTTC" + \
                     "TAATTCCTAAAACCAAAATCCAGTACTAAAATCCAGATCCCCCGAATTCCAAGCTCGAACCCCTTCGCTAGAGCTAAGACTTGTGTTTACAATTTTTTATAT" + \
                     "TTGTTTTTAAGTTTTGAATATATGTTTTCATGTGTGATTTTACCGAACAAAAATACCGGTTCCCGTCCGATTTCGACTTTAACCCGACCGGATCGTATCGGT" + \
                     "TTTCGATTACCGTATTTATCCCGTTCGTTTTCGTTACCGGTATATCCCGTTTTCGTTTCCGTCCCGCAAGTTAAATATGAAAATGAAAACGGTAGAGGTATT" + \
                     "TTACCGACCGTTCCCGACCGTTTTCATCCCTA"

        # >Ds-GFP_TAG21_ReverseComplement  (2165 bp)
        self.dsgfpRevComp = \
            "TAGGGATGAAAACGGTCGGGAACGGTCGGTAAAATACCTCTACCGTTTTCATTTTCATATTTAACTTGCGGGACGGAAACGAAAAC" + \
                            "GGGATATACCGGTAACGAAAACGAACGGGATAAATACGGTAATCGAAAACCGATACGATCCGGTCGGGTTAAAGTCGAAATCGGACGGGAACCGGTATTTTT" + \
                            "GTTCGGTAAAATCACACATGAAAACATATATTCAAAACTTAAAAACAAATATAAAAAATTGTAAACACAAGTCTTAGCTCTAGCGAAGGGGTTCGAGCTTGG" + \
                            "AATTCGGGGGATCTGGATTTTAGTACTGGATTTTGGTTTTAGGAATTAGAAATTTTATTGATAGAAGTATTTTACAAATACAAATACATACTAAGGGTTTCT" + \
                            "TATATGCTCAACACATGAGCGAAACCCTATAGGAACCCTAATTCCCTTATCTGGGAACTACTCACACATTATTATGGAGAAACTCGAGCTTGCATGCCTGCA" + \
                            "GGTCGACTCTAGAGTCGCGGCCGCTTTACTTGTACAGCTCGTCCATGCCGAGAGTGATCCCGGCGGCGGTCACGAACTCCAGCAGGACCATGTGATCGCGCT" + \
                            "TCTCGTTGGGGTCTTTGCTCAGGGCGGACTGGGTGCTCAGGTAGTGGTTGTCGGGCAGCAGCACGGGGCCGTCGCCGATGGGGGTGTTCTGCTGGTAGTGGT" + \
                            "CGGCGAGCTGCACGCTGCCGTCCTCGATGTTGTGGCGGATCTTGAAGTTCACCTTGATGCCGTTCTTCTGCTTGTCGGCCATGATATAGACGTTGTGGCTGT" + \
                            "TGTAGTTGTACTCCAGCTTGTGCCCCAGGATGTTGCCGTCCTCCTTGAAGTCGATGCCCTTCAGCTCGATGCGGTTCACCAGGGTGTCGCCCTCGAACTTCA" + \
                            "CCTCGGCGCGGGTCTTGTAGTTGCCGTCGTCCTTGAAGAAGATGGTGCGCTCCTGGACGTAGCCTTCGGGCATGGCGGACTTGAAGAAGTCGTGCTGCTTCA" + \
                            "TGTGGTCGGGGTAGCGGCTGAAGCACTGCACGCCGTAGGTCAGGGTGGTCACGAGGGTGGGCCAGGGCACGGGCAGCTTGCCGGTGGTGCAGATGAACTTCA" + \
                            "GGGTCAGCTTGCCGTAGGTGGCATCGCCCTCGCCCTCGCCGGACACGCTGAACTTGTGGCCGTTTACGTCGCCGTCCAGCTCGACCAGGATGGGCACCACCC" + \
                            "CGGTGAACAGCTCCTCGCCCTTGCTCACCATGGTGGCGACCGGTACCCGGGGATCCTCTAGATGGGTGATGGATTAACTACTGATTTGGGCGCTATTTATAT" + \
                            "AGGTGAGATCTCATATAAATTTTTTGGATTTTGTCTTTTTTTTCCAAACAACAGATAAGGTATAGATGATATGGCATCTACTCGATTTCAACATTTAGTTAT" + \
                            "CACCTTTATCGGATTATATGGTCTTTGCTGGAAAGATACTTTCCACTACCTACAAGAAAATGTGCCATTTTTATATAGGCATTCTTTTTATCTACGTGGAAT" + \
                            "GACATGCAAGATCTCTTCACCTTTACACATGTaagctCCAAGCTCGAACCCCTTCGCTAGAGCCGAGCAGTGGAGTGGAGGGCGGACCGTGGATGGCGGCGT" + \
                            "CTGCGTCCGGCGTGCCGCGTCACGGCCGTCACCGCGTGTGGTGCCTGGTGCAGCCCAGCGGCCGGCCGGCTGGGAGACAGGGAGAGTCGGAGAGAGCAGGCG" + \
                            "AGAGCGAGACGCGTCGCCGGCGTCGGCGTGCGGCTGGCGGCGTCCGGACTCCGGCGTGGGCGCGTGGCGGCGTGTGAATGTGTGATGCTGTTACTCGTGTGG" + \
                            "TGCCTGGCCGCCTGGGAGAGAGGCAGAGCAGCGTTCGCTAGGTATTTCTTACATGGGCTGGGCCTCAGTGGTTATGGATGGGAGTTGGAGCTGGCCATATTG" + \
                            "CAGTCATCCCGAATTAGAAAATACGGTAACGAAACGGGATCATTCCGATTAAAAACGGGATCCCGGTGAAACGGTCGGGAAACTAGCTCTACCGTTTCCGTT" + \
                            "TCCGTTTACCGTTTTGTATATCCCGTTTCCGTTCCGTTTTCGTTTTTTACCTCGGGTTCGAAATCGATCGGGATAAAACTAACAAAATCGGTTATACGATAA" + \
                            "CGGTCGGTACGGGATTTTCCCATCCTACTTTCATCCCTA"

        self.gfp3utr = "TGCAAGCTCGAGTTTCTCCA"  # GFP3UTR primer
        self.gfp3utrSize = "750-1000"
        self.gfp3utrHairpin = "24"

        self.dsgg3 = "TTGGAGCTGGCCATATTGCAG"  # 3DsgG primer
        self.dsgg3Size = "425-775"
        self.dsgg3Hairpin = "38"